esphome:
  name: esp32-dht22
  friendly_name: ESP32-DHT22

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ZcCKVZQKjQlOTudlqK89tgLtsWTBRKwC30cfeyYUnjU="

ota:
  - platform: esphome
    password: "3621e8c8bb25982030101fc2e5213f3e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Dht22 Fallback Hotspot"
    password: "pwkjJjbakEnI"

captive_portal:

# Sensor DHT22
sensor:
  - platform: dht
    pin: GPIO32
    temperature:
      name: "Suhu Ruangan"
    humidity:
      name: "Kelembapan Ruangan"
    update_interval: 10s
    model: DHT22
