esphome:
  name: esp32-relay8ch
  friendly_name: ESP32-RELAY8CH

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5UL+wRo7kclSWBN9iqRfruCjo+3Q0bh8FhqvOeQrMMg="

ota:
  - platform: esphome
    password: "f4d887fda947726a4f1d53cf49851a9a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Relay8Ch Fallback Hotspot"
    password: "tEMyL5g9bZ4C"

captive_portal:

switch:
  - platform: gpio
    pin: GPIO2
    name: "Relay 1"
  - platform: gpio
    pin: GPIO4
    name: "Relay 2"
  - platform: gpio
    pin: GPIO16
    name: "Relay 3"
  - platform: gpio
    pin: GPIO17
    name: "Relay 4"
  - platform: gpio
    pin: GPIO5
    name: "Relay 5"
  - platform: gpio
    pin: GPIO18
    name: "Relay 6"
  - platform: gpio
    pin: GPIO19
    name: "Relay 7"
  - platform: gpio
    pin: GPIO21
    name: "Relay 8"