esphome:
  name: "smart-relay"
  friendly_name: ESP32-RELAY

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5UL+wRo7kclSWBN9iqRfruCjo+3Q0bh8FhqvOeQrMMg="

ota:
  - platform: esphome
    password: "f4d887fda947726a4f1d53cf49851a9a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Relay8Ch Fallback Hotspot"
    password: "tEMyL5g9bZ4C"

captive_portal:

# 8 buah relay
switch:
  - platform: gpio
    id: relay1
    pin: GPIO2
    name: "Relay 1"

  - platform: gpio
    id: relay2
    pin: GPIO4
    name: "Relay 2"

  - platform: gpio
    id: relay3
    pin: GPIO16
    name: "Relay 3"

  - platform: gpio
    id: relay4
    pin: GPIO17
    name: "Relay 4"

  - platform: gpio
    id: relay5
    pin: GPIO5
    name: "Relay 5"

  - platform: gpio
    id: relay6
    pin: GPIO18
    name: "Relay 6"

  - platform: gpio
    id: relay7
    pin: GPIO19
    name: "Relay 7"

  - platform: gpio
    id: relay8
    pin: GPIO21
    name: "Relay 8"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
    name: "Tombol Relay 1"
    on_press:
      - switch.turn_on: relay1
    on_release:
      - switch.turn_off: relay1

  - platform: gpio
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
    name: "Tombol Relay 2"
    on_press:
      - switch.turn_on: relay2
    on_release:
      - switch.turn_off: relay2

  - platform: gpio
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
    name: "Tombol Relay 3"
    on_press:
      - switch.turn_on: relay3
    on_release:
      - switch.turn_off: relay3

  - platform: gpio
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
    name: "Tombol Relay 4"
    on_press:
      - switch.turn_on: relay4
    on_release:
      - switch.turn_off: relay4

  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
    name: "Tombol Relay 5"
    on_press:
      - switch.turn_on: relay5
    on_release:
      - switch.turn_off: relay5

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    name: "Tombol Relay 6"
    on_press:
      - switch.turn_on: relay6
    on_release:
      - switch.turn_off: relay6

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: "Tombol Relay 7"
    on_press:
      - switch.turn_on: relay7
    on_release:
      - switch.turn_off: relay7

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    name: "Tombol Relay 8"
    on_press:
      - switch.turn_on: relay8
    on_release:
      - switch.turn_off: relay8