esphome:
  name: camera
  friendly_name: Camera

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3bOjeij5h4tm7Ne1RyW2/4DMFIvzcdvtqJ3RNZyFILw="

ota:
  - platform: esphome
    password: "8bf8822d93d6d7bbcbbd19e761ffd922"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camera Fallback Hotspot"
    password: "KuILqd03I5wY"

captive_portal:
    