esphome:
  name: esp32-s3-wake-word
  friendly_name: ESP32-S3-WAKE-WORD
  platformio_options:
    board_build.flash_mode: dio
    platform: espressif32@6.5.0

  on_boot:
    - light.turn_on:
        id: led_ww
        effect: "Rainbow Effect"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0

api:
  encryption:
    key: "uLUhcJ2NoHb0mD855P2y5IgOJ30FUvkrJ3hK117RvJQ="
  on_client_connected:
    then:
      - delay: 50ms
      - light.turn_off: led_ww
      - micro_wake_word.start:
  on_client_disconnected:
    then:
      - voice_assistant.stop:

ota:
  - platform: esphome
    password: "62bb62e0bd67a2b9b24cf4d53249e7c9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp32-S3-Wake-Word"
    password: "fsqLfMdkLfgq"

captive_portal:

button:
  - platform: restart
    name: "Restart"
    id: but_rest

switch:
  - platform: template
    id: mute
    name: mute
    optimistic: true
    on_turn_on: 
      - micro_wake_word.stop:
      - voice_assistant.stop:
      - light.turn_on:
          id: led_ww           
          red: 100%
          green: 0%
          blue: 0%
          brightness: 60%
          effect: fast pulse 
      - delay: 2s
      - light.turn_off:
          id: led_ww
      - light.turn_on:
          id: led_ww           
          red: 100%
          green: 0%
          blue: 0%
          brightness: 30%
    on_turn_off:
      - micro_wake_word.start:
      - light.turn_on:
          id: led_ww           
          red: 0%
          green: 100%
          blue: 0%
          brightness: 60%
          effect: fast pulse 
      - delay: 2s
      - light.turn_off:
          id: led_ww 

light:
  - platform: esp32_rmt_led_strip
    id: led_ww
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    chipset: ws2812
    name: "on board light"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%

# Audio Configuration
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO3  # WS
    i2s_bclk_pin: GPIO2   # SCK
  - id: i2s_out
    i2s_lrclk_pin: GPIO39  # LRC
    i2s_bclk_pin: GPIO38   # BCLK

microphone:
  - platform: i2s_audio
    id: va_mic
    adc_type: external
    i2s_din_pin: GPIO4     # SD pin on the INMP441
    channel: left
    pdm: false
    i2s_audio_id: i2s_in
    bits_per_sample: 32 bit

speaker:
  platform: i2s_audio
  id: va_speaker
  i2s_audio_id: i2s_out
  dac_type: external
  i2s_dout_pin: GPIO40      # DIN
  channel: mono

# Wake Word and Voice Assistant
micro_wake_word:
  on_wake_word_detected:
    then:
      - voice_assistant.start:
          wake_word: !lambda return wake_word;
      - light.turn_on:
          id: led_ww
          red: 30%
          green: 30%
          blue: 70%
          brightness: 60%
          effect: fast pulse 
  models:
    - model: okay_nabu

voice_assistant:
  id: va
  microphone: va_mic
  speaker: va_speaker
  volume_multiplier: 4.0
  noise_suppression_level: 2.0
  on_stt_end:
    then:
      - light.turn_off: led_ww
  on_end:
    then:
      - light.turn_off: led_ww
      - wait_until:
          not:
            voice_assistant.is_running:
      - micro_wake_word.start:
  on_error:
    then:
      - micro_wake_word.start:
