esphome:
  name: home
  friendly_name: Home

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5YCjyJmengbU3FCZMo0XnPN8pQsC6i8Bw+pSk7IMQB0="

ota:
  - platform: esphome
    password: "adbc2e52dc5f4960565de5a0e6fc9360"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Home Fallback Hotspot"
    password: "CcHDnAmj0pQA"

captive_portal:
    