esphome:
  name: voiceeee
  friendly_name: voiceeee

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dOXJg5sRlwJy1udKSleGbf+tYQMYKr2Qz7XggVrmDVI="

ota:
  - platform: esphome
    password: "7da313092df30f86663f269a7cf6280e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Voiceeee Fallback Hotspot"
    password: "DNmhlA0At03J"

captive_portal:
# I2S Audio Configuration (untuk MAX98357A)
i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO26

media_player:
  - platform: i2s_audio
    name: "Speaker ESP32"
    id: my_speaker
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO22
    mode: mono

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
